### ISSUE TITLE
Chrysalis 0.10.0(?) TODO

### ISSUE THREAD

**Issue by algernon** [keyboardio/Chrysalis#865]
I'm planning to cut a 0.10.0 release soon, and to not forget a couple of non-automated steps, here's a checklist:

- [x] Bump the version to 0.10.0-snapshot, and adjust it in NEWS.md aswell
- [x] Add the more recent developments to NEWS
- [x] Update the screenshot
- [x] Cut the release

**Comment by obra** [comment]
(It would be great for all of these steps to be in doc/releasing.md
